create table if not exists public.keepalive_events (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  created_at timestamptz not null default now()
);

alter table public.keepalive_events enable row level security;

create policy if not exists "service_role_all_access" on public.keepalive_events
for all
to service_role
using (true)
with check (true);
